version: "3"

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./:/app

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env